spring:
  datasource:
    url: jdbc:h2:mem:bdh2
    username: userdev
    password: 123
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create #validade | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
    h2:
      console:
        enable: true
        path: /h2-console
        settings:
          trace: false
          web-allow-others: false